---
deployment:
  tasks:
    - export DEPLOYPATH=/home/chri50817861/public_html/isosearcher
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH